export const actionTypes = {
  GET_DATA_START: "GET_DATA_START",
  GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
  GET_DATA_ERROR: "GET_DATA_ERROR",
  TOGGLE_CHECKOUT_MODAL: "TOGGLE_CHECKOUT_MODAL",
  TOGGLE_CHECKOUT_MODAL_CLOSE: "TOGGLE_CHECKOUT_MODAL_CLOSE",
  UPDATE_QUANTITY: "UPDATE_QUANTITY",
  DELETE_AN_ITEM_FROM_CART: "DELETE_AN_ITEM_FROM_CART",
  PAY_BUTTON: "PAY_BUTTON",
  ADD_TO_CART: "ADD_TO_CART",
  CLEAR_RECEIPT: "CLEAR_RECEIPT",
};
